version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"  # Necesario para agentes JNLP
    volumes:
      - jenkins_home:/var/jenkins_home
    user: root
    restart: unless-stopped

  agent:
    image: jenkins/inbound-agent:alpine-jdk17
    container_name: jenkins-agent
    depends_on:
      - jenkins
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=agente1
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JENKINS_SECRET=REEMPLAZAR_CON_EL_TOKEN_DEL_AGENT
    restart: unless-stopped

volumes:
  jenkins_home:
